version: '3.8'
services:
    db:
        container_name: altria_db
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: altria
        ports:
            - "5432:5432"
        volumes:
            - ./pg_data:/var/lib/postgresql/data/
            - ./startup.sh:/docker-entrypoint-initdb.d/startup.sh
        extra_hosts: 
            - "db:192.168.1.13"

volumes:
  pg_data:  
  pgadmin-data: